# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: twopc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'twopc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btwopc.proto\x12\x05twopc\"\x85\x01\n\x0bVoteRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x11\n\tfile_data\x18\x04 \x01(\t\x12\x15\n\rmetadata_json\x18\x05 \x01(\t\x12\x0f\n\x07node_id\x18\x06 \x01(\t\"E\n\x0cVoteResponse\x12\x13\n\x0bvote_commit\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07node_id\x18\x03 \x01(\t\"Q\n\x0f\x44\x65\x63isionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x15\n\rglobal_commit\x18\x02 \x01(\x08\x12\x0f\n\x07node_id\x18\x03 \x01(\t\"E\n\x10\x44\x65\x63isionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07node_id\x18\x03 \x01(\t2C\n\x10VotePhaseService\x12/\n\x04Vote\x12\x12.twopc.VoteRequest\x1a\x13.twopc.VoteResponse2S\n\x14\x44\x65\x63isionPhaseService\x12;\n\x08\x44\x65\x63ision\x12\x16.twopc.DecisionRequest\x1a\x17.twopc.DecisionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'twopc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTEREQUEST']._serialized_start=23
  _globals['_VOTEREQUEST']._serialized_end=156
  _globals['_VOTERESPONSE']._serialized_start=158
  _globals['_VOTERESPONSE']._serialized_end=227
  _globals['_DECISIONREQUEST']._serialized_start=229
  _globals['_DECISIONREQUEST']._serialized_end=310
  _globals['_DECISIONRESPONSE']._serialized_start=312
  _globals['_DECISIONRESPONSE']._serialized_end=381
  _globals['_VOTEPHASESERVICE']._serialized_start=383
  _globals['_VOTEPHASESERVICE']._serialized_end=450
  _globals['_DECISIONPHASESERVICE']._serialized_start=452
  _globals['_DECISIONPHASESERVICE']._serialized_end=535
# @@protoc_insertion_point(module_scope)
